---
title: "262hw1"
author: "Elizabeth Braun"
date: "2024-02-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

I'm taking this course because it seemed like a good way to boost my R skills and overall understanding of programming and data science overall. I really like how it feels very low-stakes and accessible (much credit to Louis and Ojas for that) and so it seems kind of like a 206 remedial course, which I very much appreciate. It also seems like a good way to just have a more thorough understanding of how the program works which I feel like a lot of people might not have gotten in 206 as there was so much to get through in such a short time.

My data science background isn't much. I took 206 but I did poorly because I had a lot of family issues at the time and so I ended up turning in the majority of the labs late, and didn't get more than 1/3rd of the way through the (optional) final project. I've avoided coding or any kind of data science since because it kind of brought down my confidence, and I've reached out to students who took the new updated version of that course because Chris Jerde told me he had spent a lot of time updating it and felt the same way I did about how it went in 2022. In all the classes I've done since that involved using R for any portion of the homework assignments I've elected to contribute in any other way except doing R. But, when I look over coding lessons, it feels familiar and not incredibly overwhelming. I think I just missed a lot of little details that help everything run a lot smoother, but generally had the big picture down pretty well.
