---
title: "hw5"
author: "Elizabeth Braun"
date: "2024-03-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)

possible.fish = c("salmon","steelhead","shark", "tuna", "cod")

```

```{r}
fish_summary = function(fish) {
  max = names(which.max(summary_fish))
  rare = names(which.min(summary_fish))
  nfish = length(fish)
  return(list(most_common=max, rarest=rare, nfish=nfish))}

```

```{r}
fish_summary2 = function(fish) {
  fish_fact = as.factor(fish)
  fish_sum = summary (fish_fact)
  rarefish = names(which.min(fish_sum))
  commonfish = names(which.max(fish_sum))
  nfish = length(fish)
  return(list(rarefish=rarefish, commonfish=commonfish, nfish=nfish))
}
```

```{r}
fish_summary2 = function(fish) {
  fish_fact = as.factor(fish)
  fish_sum = summary (fish_fact)
  rarefish = names(which.min(fish_sum))
  commonfish = names(which.max(fish_sum))
  nfish = length(fish)
  return(list(rarefish=rarefish, commonfish=commonfish, nfish=nfish))
}
```
